[package]
authors     = ["The Fish Fight Game & Spicy Lobster Developers"]
default-run = "jumpy"
description = "A tactical 2D shooter"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "jumpy"
version     = "0.5.1"

[workspace]
members = [".", "core"]

[features]
default = ["render"]
render  = ["bevy/x11", "bevy/png", "bevy/filesystem_watcher", "bevy/bevy_gilrs"]

[dependencies]

anyhow                 = "1.0.58"
async-channel          = "1.7.1"
base64                 = "0.21.0"
bevy-inspector-egui    = { version = "0.17.0" }
bevy_egui              = "0.19.0"
bevy_fluent            = "0.5.0"
bevy_framepace         = "0.11.0"
bevy_kira_audio        = { version = "0.13.0", features = ["ogg"], default-features = false }
bevy_prototype_lyon    = "0.7.2"
bevy_tweening          = { version = "0.6.0", default-features = false }
bones_bevy_asset       = "0.1.0"
bones_bevy_renderer    = "0.1.1"
bones_lib              = { version = "0.1.0", features = ["bevy"] }
bytemuck               = "1.12.3"
clap                   = { version = "4.0.18", features = ["derive", "env"] }
directories            = "4.0.1"
egui_extras            = "0.20.0"
either                 = "1.8.0"
fluent                 = "0.16.0"
fluent_content         = "0.0.3"
fnv                    = "1.0.7"
futures-lite           = "1.12.0"
getrandom              = { version = "0.2", features = ["js"] }
iyes_loopless          = "0.9.1"
jumpy_core             = { path = "./core" }
leafwing-input-manager = { version = "0.8.0", default-features = false }
log                    = { version = "0.4.17", features = ["release_max_level_debug"] }
normalize-path         = "0.2.0"
once_cell              = "1.17.0"
rand                   = "0.8.5"
serde                  = { version = "1.0.137", features = ["derive"] }
serde_json             = "1.0.89"
serde_yaml             = "0.9.2"
thiserror              = "1.0.31"
tracing                = { version = "0.1.37", features = ["release_max_level_debug"] }
type_ulid              = "0.1.0"
unic-langid            = "0.9.0"

[dependencies.bevy]
default-features = false
features         = ["x11", "png", "filesystem_watcher", "bevy_gilrs"]
version          = "0.9.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.83"
web-sys      = { version = "0.3", features = ["Window", "Location", "Storage"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mimalloc = { version = "0.1.32", default-features = false }

# Optimize dependencies even in development
[profile.dev.package."*"]
opt-level = 3

# Optimize our code a little bit.
#
# Set these to 3 if the game becomes slow to respond during gameplay,
# or change them to 0 to get faster re-compiles.
[profile.dev.package.jumpy_core]
opt-level = 1
[profile.dev]
opt-level = 1 

[profile.release]
codegen-units = 1    # Improved rapier physics perf, so it might help other stuff, too
lto           = true

[patch.crates-io]
bones_lib = { git = "https://github.com/fishfolk/bones" }
bones_bevy_asset = { git = "https://github.com/fishfolk/bones" }
type_ulid = { git = "https://github.com/fishfolk/bones" }
bones_bevy_renderer = { git = "https://github.com/fishfolk/bones" }
